# -------------------------------------------------
#               FILE PATHS
# -------------------------------------------------
# This section defines the directory structure for the project.
data:
  raw: 'data/raw/'
  processed: 'data/processed/'
  metadata: 'data/metadata/'
  external: 'data/external/'

outputs:
  models: 'outputs/models/'
  reports: 'outputs/reports/'
  visualizations: 'outputs/visualizations/'

src: 'src/'

# -------------------------------------------------
#              DATA SETTINGS
# -------------------------------------------------
# This section defines parameters for data loading and processing.
hmda_data:
  target_variable: 'action_taken'
  initial_year_to_load: 2008 # Start with one year for initial analysis